favicon: null
name: Ever The Patriot
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7105539
  brandStrength: 0.4728366478811949
  lightness: 0.931903
  brandColors:
    - '#fefefe'
    - '#242178'
    - '#cb1d1e'
    - '#808080'
    - '#cacaca'
  rhythmicContrast: 0.9734911
typography_spectrum: 0.24684
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.48789
analytics:
  twitter: null
  google: null
  facebook: null
