name: Ever The Patriot
favicon: null
layout_spectrum: 0.48789
typography_spectrum: 0.24684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#242178'
    - '#cb1d1e'
    - '#808080'
    - '#cacaca'
  brandStrength: 0.47283664788119495
  lightness: 0.9395672786049545
  saturation: 0.7105539233889431
  rhythmicContrast: 0.9734910714905709
purpose: []
